// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://seszngamvirqtszulzmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlc3puZ2FtdmlycXRzenVsem1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3ODQwMTAsImV4cCI6MjA3MDM2MDAxMH0.6rBCoanM9p9Qh1q-O3AIbB-LXfZ7jM04IIGKJ2T8FoM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});