// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbdfqjkxabocmalolhmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRiZGZxamt4YWJvY21hbG9saG1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1MjYyNDAsImV4cCI6MjA4NDEwMjI0MH0.u0XrbT2dVUAUuN-u-TX2TE48KpbtfULRaOh0xXhfJCs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});